# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /u/f/a/fanj/local/bin/cmake

# The command to remove a file.
RM = /u/f/a/fanj/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /u/f/a/fanj/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /u/f/a/fanj/aggregation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /u/f/a/fanj/aggregation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/afs/cs.wisc.edu/u/f/a/fanj/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/afs/cs.wisc.edu/u/f/a/fanj/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /u/f/a/fanj/aggregation/CMakeFiles /u/f/a/fanj/aggregation/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /u/f/a/fanj/aggregation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named util_idf

# Build rule for target.
util_idf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 util_idf
.PHONY : util_idf

# fast build rule for target.
util_idf/fast:
	$(MAKE) -f CMakeFiles/util_idf.dir/build.make CMakeFiles/util_idf.dir/build
.PHONY : util_idf/fast

#=============================================================================
# Target rules for targets named util_preprocess

# Build rule for target.
util_preprocess: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 util_preprocess
.PHONY : util_preprocess

# fast build rule for target.
util_preprocess/fast:
	$(MAKE) -f CMakeFiles/util_preprocess.dir/build.make CMakeFiles/util_preprocess.dir/build
.PHONY : util_preprocess/fast

#=============================================================================
# Target rules for targets named util_similarity

# Build rule for target.
util_similarity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 util_similarity
.PHONY : util_similarity

# fast build rule for target.
util_similarity/fast:
	$(MAKE) -f CMakeFiles/util_similarity.dir/build.make CMakeFiles/util_similarity.dir/build
.PHONY : util_similarity/fast

main.o: main.cc.o
.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cc.s
.PHONY : main.cc.s

src/aggregation.o: src/aggregation.cc.o
.PHONY : src/aggregation.o

# target to build an object file
src/aggregation.cc.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/aggregation.cc.o
.PHONY : src/aggregation.cc.o

src/aggregation.i: src/aggregation.cc.i
.PHONY : src/aggregation.i

# target to preprocess a source file
src/aggregation.cc.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/aggregation.cc.i
.PHONY : src/aggregation.cc.i

src/aggregation.s: src/aggregation.cc.s
.PHONY : src/aggregation.s

# target to generate assembly for a file
src/aggregation.cc.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/aggregation.cc.s
.PHONY : src/aggregation.cc.s

src/arxiv_reader.o: src/arxiv_reader.cc.o
.PHONY : src/arxiv_reader.o

# target to build an object file
src/arxiv_reader.cc.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/arxiv_reader.cc.o
	$(MAKE) -f CMakeFiles/util_idf.dir/build.make CMakeFiles/util_idf.dir/src/arxiv_reader.cc.o
.PHONY : src/arxiv_reader.cc.o

src/arxiv_reader.i: src/arxiv_reader.cc.i
.PHONY : src/arxiv_reader.i

# target to preprocess a source file
src/arxiv_reader.cc.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/arxiv_reader.cc.i
	$(MAKE) -f CMakeFiles/util_idf.dir/build.make CMakeFiles/util_idf.dir/src/arxiv_reader.cc.i
.PHONY : src/arxiv_reader.cc.i

src/arxiv_reader.s: src/arxiv_reader.cc.s
.PHONY : src/arxiv_reader.s

# target to generate assembly for a file
src/arxiv_reader.cc.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/arxiv_reader.cc.s
	$(MAKE) -f CMakeFiles/util_idf.dir/build.make CMakeFiles/util_idf.dir/src/arxiv_reader.cc.s
.PHONY : src/arxiv_reader.cc.s

src/graph.o: src/graph.cc.o
.PHONY : src/graph.o

# target to build an object file
src/graph.cc.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/graph.cc.o
	$(MAKE) -f CMakeFiles/util_idf.dir/build.make CMakeFiles/util_idf.dir/src/graph.cc.o
.PHONY : src/graph.cc.o

src/graph.i: src/graph.cc.i
.PHONY : src/graph.i

# target to preprocess a source file
src/graph.cc.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/graph.cc.i
	$(MAKE) -f CMakeFiles/util_idf.dir/build.make CMakeFiles/util_idf.dir/src/graph.cc.i
.PHONY : src/graph.cc.i

src/graph.s: src/graph.cc.s
.PHONY : src/graph.s

# target to generate assembly for a file
src/graph.cc.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/graph.cc.s
	$(MAKE) -f CMakeFiles/util_idf.dir/build.make CMakeFiles/util_idf.dir/src/graph.cc.s
.PHONY : src/graph.cc.s

src/idf_gen.o: src/idf_gen.cc.o
.PHONY : src/idf_gen.o

# target to build an object file
src/idf_gen.cc.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/idf_gen.cc.o
	$(MAKE) -f CMakeFiles/util_idf.dir/build.make CMakeFiles/util_idf.dir/src/idf_gen.cc.o
.PHONY : src/idf_gen.cc.o

src/idf_gen.i: src/idf_gen.cc.i
.PHONY : src/idf_gen.i

# target to preprocess a source file
src/idf_gen.cc.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/idf_gen.cc.i
	$(MAKE) -f CMakeFiles/util_idf.dir/build.make CMakeFiles/util_idf.dir/src/idf_gen.cc.i
.PHONY : src/idf_gen.cc.i

src/idf_gen.s: src/idf_gen.cc.s
.PHONY : src/idf_gen.s

# target to generate assembly for a file
src/idf_gen.cc.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/idf_gen.cc.s
	$(MAKE) -f CMakeFiles/util_idf.dir/build.make CMakeFiles/util_idf.dir/src/idf_gen.cc.s
.PHONY : src/idf_gen.cc.s

src/jaccard_ranker.o: src/jaccard_ranker.cc.o
.PHONY : src/jaccard_ranker.o

# target to build an object file
src/jaccard_ranker.cc.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/jaccard_ranker.cc.o
.PHONY : src/jaccard_ranker.cc.o

src/jaccard_ranker.i: src/jaccard_ranker.cc.i
.PHONY : src/jaccard_ranker.i

# target to preprocess a source file
src/jaccard_ranker.cc.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/jaccard_ranker.cc.i
.PHONY : src/jaccard_ranker.cc.i

src/jaccard_ranker.s: src/jaccard_ranker.cc.s
.PHONY : src/jaccard_ranker.s

# target to generate assembly for a file
src/jaccard_ranker.cc.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/jaccard_ranker.cc.s
.PHONY : src/jaccard_ranker.cc.s

src/meta_data.o: src/meta_data.cc.o
.PHONY : src/meta_data.o

# target to build an object file
src/meta_data.cc.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/meta_data.cc.o
	$(MAKE) -f CMakeFiles/util_idf.dir/build.make CMakeFiles/util_idf.dir/src/meta_data.cc.o
.PHONY : src/meta_data.cc.o

src/meta_data.i: src/meta_data.cc.i
.PHONY : src/meta_data.i

# target to preprocess a source file
src/meta_data.cc.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/meta_data.cc.i
	$(MAKE) -f CMakeFiles/util_idf.dir/build.make CMakeFiles/util_idf.dir/src/meta_data.cc.i
.PHONY : src/meta_data.cc.i

src/meta_data.s: src/meta_data.cc.s
.PHONY : src/meta_data.s

# target to generate assembly for a file
src/meta_data.cc.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/meta_data.cc.s
	$(MAKE) -f CMakeFiles/util_idf.dir/build.make CMakeFiles/util_idf.dir/src/meta_data.cc.s
.PHONY : src/meta_data.cc.s

src/option.o: src/option.cc.o
.PHONY : src/option.o

# target to build an object file
src/option.cc.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/option.cc.o
	$(MAKE) -f CMakeFiles/util_idf.dir/build.make CMakeFiles/util_idf.dir/src/option.cc.o
	$(MAKE) -f CMakeFiles/util_similarity.dir/build.make CMakeFiles/util_similarity.dir/src/option.cc.o
.PHONY : src/option.cc.o

src/option.i: src/option.cc.i
.PHONY : src/option.i

# target to preprocess a source file
src/option.cc.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/option.cc.i
	$(MAKE) -f CMakeFiles/util_idf.dir/build.make CMakeFiles/util_idf.dir/src/option.cc.i
	$(MAKE) -f CMakeFiles/util_similarity.dir/build.make CMakeFiles/util_similarity.dir/src/option.cc.i
.PHONY : src/option.cc.i

src/option.s: src/option.cc.s
.PHONY : src/option.s

# target to generate assembly for a file
src/option.cc.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/option.cc.s
	$(MAKE) -f CMakeFiles/util_idf.dir/build.make CMakeFiles/util_idf.dir/src/option.cc.s
	$(MAKE) -f CMakeFiles/util_similarity.dir/build.make CMakeFiles/util_similarity.dir/src/option.cc.s
.PHONY : src/option.cc.s

src/post_reader.o: src/post_reader.cc.o
.PHONY : src/post_reader.o

# target to build an object file
src/post_reader.cc.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/post_reader.cc.o
	$(MAKE) -f CMakeFiles/util_idf.dir/build.make CMakeFiles/util_idf.dir/src/post_reader.cc.o
.PHONY : src/post_reader.cc.o

src/post_reader.i: src/post_reader.cc.i
.PHONY : src/post_reader.i

# target to preprocess a source file
src/post_reader.cc.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/post_reader.cc.i
	$(MAKE) -f CMakeFiles/util_idf.dir/build.make CMakeFiles/util_idf.dir/src/post_reader.cc.i
.PHONY : src/post_reader.cc.i

src/post_reader.s: src/post_reader.cc.s
.PHONY : src/post_reader.s

# target to generate assembly for a file
src/post_reader.cc.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/post_reader.cc.s
	$(MAKE) -f CMakeFiles/util_idf.dir/build.make CMakeFiles/util_idf.dir/src/post_reader.cc.s
.PHONY : src/post_reader.cc.s

src/preprocess.o: src/preprocess.cc.o
.PHONY : src/preprocess.o

# target to build an object file
src/preprocess.cc.o:
	$(MAKE) -f CMakeFiles/util_preprocess.dir/build.make CMakeFiles/util_preprocess.dir/src/preprocess.cc.o
.PHONY : src/preprocess.cc.o

src/preprocess.i: src/preprocess.cc.i
.PHONY : src/preprocess.i

# target to preprocess a source file
src/preprocess.cc.i:
	$(MAKE) -f CMakeFiles/util_preprocess.dir/build.make CMakeFiles/util_preprocess.dir/src/preprocess.cc.i
.PHONY : src/preprocess.cc.i

src/preprocess.s: src/preprocess.cc.s
.PHONY : src/preprocess.s

# target to generate assembly for a file
src/preprocess.cc.s:
	$(MAKE) -f CMakeFiles/util_preprocess.dir/build.make CMakeFiles/util_preprocess.dir/src/preprocess.cc.s
.PHONY : src/preprocess.cc.s

src/ranker.o: src/ranker.cc.o
.PHONY : src/ranker.o

# target to build an object file
src/ranker.cc.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ranker.cc.o
.PHONY : src/ranker.cc.o

src/ranker.i: src/ranker.cc.i
.PHONY : src/ranker.i

# target to preprocess a source file
src/ranker.cc.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ranker.cc.i
.PHONY : src/ranker.cc.i

src/ranker.s: src/ranker.cc.s
.PHONY : src/ranker.s

# target to generate assembly for a file
src/ranker.cc.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ranker.cc.s
.PHONY : src/ranker.cc.s

src/similarity.o: src/similarity.cc.o
.PHONY : src/similarity.o

# target to build an object file
src/similarity.cc.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/similarity.cc.o
	$(MAKE) -f CMakeFiles/util_similarity.dir/build.make CMakeFiles/util_similarity.dir/src/similarity.cc.o
.PHONY : src/similarity.cc.o

src/similarity.i: src/similarity.cc.i
.PHONY : src/similarity.i

# target to preprocess a source file
src/similarity.cc.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/similarity.cc.i
	$(MAKE) -f CMakeFiles/util_similarity.dir/build.make CMakeFiles/util_similarity.dir/src/similarity.cc.i
.PHONY : src/similarity.cc.i

src/similarity.s: src/similarity.cc.s
.PHONY : src/similarity.s

# target to generate assembly for a file
src/similarity.cc.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/similarity.cc.s
	$(MAKE) -f CMakeFiles/util_similarity.dir/build.make CMakeFiles/util_similarity.dir/src/similarity.cc.s
.PHONY : src/similarity.cc.s

src/string_util.o: src/string_util.cc.o
.PHONY : src/string_util.o

# target to build an object file
src/string_util.cc.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/string_util.cc.o
	$(MAKE) -f CMakeFiles/util_idf.dir/build.make CMakeFiles/util_idf.dir/src/string_util.cc.o
	$(MAKE) -f CMakeFiles/util_preprocess.dir/build.make CMakeFiles/util_preprocess.dir/src/string_util.cc.o
	$(MAKE) -f CMakeFiles/util_similarity.dir/build.make CMakeFiles/util_similarity.dir/src/string_util.cc.o
.PHONY : src/string_util.cc.o

src/string_util.i: src/string_util.cc.i
.PHONY : src/string_util.i

# target to preprocess a source file
src/string_util.cc.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/string_util.cc.i
	$(MAKE) -f CMakeFiles/util_idf.dir/build.make CMakeFiles/util_idf.dir/src/string_util.cc.i
	$(MAKE) -f CMakeFiles/util_preprocess.dir/build.make CMakeFiles/util_preprocess.dir/src/string_util.cc.i
	$(MAKE) -f CMakeFiles/util_similarity.dir/build.make CMakeFiles/util_similarity.dir/src/string_util.cc.i
.PHONY : src/string_util.cc.i

src/string_util.s: src/string_util.cc.s
.PHONY : src/string_util.s

# target to generate assembly for a file
src/string_util.cc.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/string_util.cc.s
	$(MAKE) -f CMakeFiles/util_idf.dir/build.make CMakeFiles/util_idf.dir/src/string_util.cc.s
	$(MAKE) -f CMakeFiles/util_preprocess.dir/build.make CMakeFiles/util_preprocess.dir/src/string_util.cc.s
	$(MAKE) -f CMakeFiles/util_similarity.dir/build.make CMakeFiles/util_similarity.dir/src/string_util.cc.s
.PHONY : src/string_util.cc.s

src/submodular_ranker.o: src/submodular_ranker.cc.o
.PHONY : src/submodular_ranker.o

# target to build an object file
src/submodular_ranker.cc.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/submodular_ranker.cc.o
.PHONY : src/submodular_ranker.cc.o

src/submodular_ranker.i: src/submodular_ranker.cc.i
.PHONY : src/submodular_ranker.i

# target to preprocess a source file
src/submodular_ranker.cc.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/submodular_ranker.cc.i
.PHONY : src/submodular_ranker.cc.i

src/submodular_ranker.s: src/submodular_ranker.cc.s
.PHONY : src/submodular_ranker.s

# target to generate assembly for a file
src/submodular_ranker.cc.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/submodular_ranker.cc.s
.PHONY : src/submodular_ranker.cc.s

src/tfidf_ranker.o: src/tfidf_ranker.cc.o
.PHONY : src/tfidf_ranker.o

# target to build an object file
src/tfidf_ranker.cc.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/tfidf_ranker.cc.o
.PHONY : src/tfidf_ranker.cc.o

src/tfidf_ranker.i: src/tfidf_ranker.cc.i
.PHONY : src/tfidf_ranker.i

# target to preprocess a source file
src/tfidf_ranker.cc.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/tfidf_ranker.cc.i
.PHONY : src/tfidf_ranker.cc.i

src/tfidf_ranker.s: src/tfidf_ranker.cc.s
.PHONY : src/tfidf_ranker.s

# target to generate assembly for a file
src/tfidf_ranker.cc.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/tfidf_ranker.cc.s
.PHONY : src/tfidf_ranker.cc.s

util/util_idf.o: util/util_idf.cc.o
.PHONY : util/util_idf.o

# target to build an object file
util/util_idf.cc.o:
	$(MAKE) -f CMakeFiles/util_idf.dir/build.make CMakeFiles/util_idf.dir/util/util_idf.cc.o
.PHONY : util/util_idf.cc.o

util/util_idf.i: util/util_idf.cc.i
.PHONY : util/util_idf.i

# target to preprocess a source file
util/util_idf.cc.i:
	$(MAKE) -f CMakeFiles/util_idf.dir/build.make CMakeFiles/util_idf.dir/util/util_idf.cc.i
.PHONY : util/util_idf.cc.i

util/util_idf.s: util/util_idf.cc.s
.PHONY : util/util_idf.s

# target to generate assembly for a file
util/util_idf.cc.s:
	$(MAKE) -f CMakeFiles/util_idf.dir/build.make CMakeFiles/util_idf.dir/util/util_idf.cc.s
.PHONY : util/util_idf.cc.s

util/util_preprocess.o: util/util_preprocess.cc.o
.PHONY : util/util_preprocess.o

# target to build an object file
util/util_preprocess.cc.o:
	$(MAKE) -f CMakeFiles/util_preprocess.dir/build.make CMakeFiles/util_preprocess.dir/util/util_preprocess.cc.o
.PHONY : util/util_preprocess.cc.o

util/util_preprocess.i: util/util_preprocess.cc.i
.PHONY : util/util_preprocess.i

# target to preprocess a source file
util/util_preprocess.cc.i:
	$(MAKE) -f CMakeFiles/util_preprocess.dir/build.make CMakeFiles/util_preprocess.dir/util/util_preprocess.cc.i
.PHONY : util/util_preprocess.cc.i

util/util_preprocess.s: util/util_preprocess.cc.s
.PHONY : util/util_preprocess.s

# target to generate assembly for a file
util/util_preprocess.cc.s:
	$(MAKE) -f CMakeFiles/util_preprocess.dir/build.make CMakeFiles/util_preprocess.dir/util/util_preprocess.cc.s
.PHONY : util/util_preprocess.cc.s

util/util_similarity.o: util/util_similarity.cc.o
.PHONY : util/util_similarity.o

# target to build an object file
util/util_similarity.cc.o:
	$(MAKE) -f CMakeFiles/util_similarity.dir/build.make CMakeFiles/util_similarity.dir/util/util_similarity.cc.o
.PHONY : util/util_similarity.cc.o

util/util_similarity.i: util/util_similarity.cc.i
.PHONY : util/util_similarity.i

# target to preprocess a source file
util/util_similarity.cc.i:
	$(MAKE) -f CMakeFiles/util_similarity.dir/build.make CMakeFiles/util_similarity.dir/util/util_similarity.cc.i
.PHONY : util/util_similarity.cc.i

util/util_similarity.s: util/util_similarity.cc.s
.PHONY : util/util_similarity.s

# target to generate assembly for a file
util/util_similarity.cc.s:
	$(MAKE) -f CMakeFiles/util_similarity.dir/build.make CMakeFiles/util_similarity.dir/util/util_similarity.cc.s
.PHONY : util/util_similarity.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... rebuild_cache"
	@echo "... util_idf"
	@echo "... util_preprocess"
	@echo "... util_similarity"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/aggregation.o"
	@echo "... src/aggregation.i"
	@echo "... src/aggregation.s"
	@echo "... src/arxiv_reader.o"
	@echo "... src/arxiv_reader.i"
	@echo "... src/arxiv_reader.s"
	@echo "... src/graph.o"
	@echo "... src/graph.i"
	@echo "... src/graph.s"
	@echo "... src/idf_gen.o"
	@echo "... src/idf_gen.i"
	@echo "... src/idf_gen.s"
	@echo "... src/jaccard_ranker.o"
	@echo "... src/jaccard_ranker.i"
	@echo "... src/jaccard_ranker.s"
	@echo "... src/meta_data.o"
	@echo "... src/meta_data.i"
	@echo "... src/meta_data.s"
	@echo "... src/option.o"
	@echo "... src/option.i"
	@echo "... src/option.s"
	@echo "... src/post_reader.o"
	@echo "... src/post_reader.i"
	@echo "... src/post_reader.s"
	@echo "... src/preprocess.o"
	@echo "... src/preprocess.i"
	@echo "... src/preprocess.s"
	@echo "... src/ranker.o"
	@echo "... src/ranker.i"
	@echo "... src/ranker.s"
	@echo "... src/similarity.o"
	@echo "... src/similarity.i"
	@echo "... src/similarity.s"
	@echo "... src/string_util.o"
	@echo "... src/string_util.i"
	@echo "... src/string_util.s"
	@echo "... src/submodular_ranker.o"
	@echo "... src/submodular_ranker.i"
	@echo "... src/submodular_ranker.s"
	@echo "... src/tfidf_ranker.o"
	@echo "... src/tfidf_ranker.i"
	@echo "... src/tfidf_ranker.s"
	@echo "... util/util_idf.o"
	@echo "... util/util_idf.i"
	@echo "... util/util_idf.s"
	@echo "... util/util_preprocess.o"
	@echo "... util/util_preprocess.i"
	@echo "... util/util_preprocess.s"
	@echo "... util/util_similarity.o"
	@echo "... util/util_similarity.i"
	@echo "... util/util_similarity.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

